project:
  type: website
  output-dir: docs
  render:
    - "*"
    - "!CHANGELOG.md"
    - "!LICENSE.md"
    - "!docs/"

website:
  title: "Alaska Region Data Management Guide"
  description: "General data management guidance and best practices for Alaska Region staff"
  favicon: ak-forum-icon_200-tr.png
  page-navigation: true
  repo-url: https://github.com/USFWS/ak-dm-guide
#  issue-url: Https://www.fws.gov
  repo-actions: [edit, issue, source]
  other-links:
    - text: Submit Feedback or suggest a change
      icon: file-text
      href: https://doimspp.sharepoint.com/sites/fws-FF07D00000
  page-footer:
    center: 
      - text: "DM Contacts"
        href: https://doimspp.sharepoint.com/sites/fws-FF07S00000-data/SitePages/Contacts.aspx
      - text: "License"
        href: license.md
      - text: "Trademark"
        href: trademark.qmd
    right:
      - text: "Page updated: {{< meta date >}}"
  
  search:
    location: sidebar
    type: textbox

  sidebar:
    style: docked
    background: light
    contents: auto
#    contents:    
#      - alaska-data-management-101/*
#      - planning/index.md
#      
#      - section: "section 1"
#        contents: index.md
#        
#          - href: "alaska-data-management-101"
#          
#      - section: "Section 2"
#        contents: auto
#        
#        contents:
#          - text: Plan
#            href: "planning"
#          
#      - section: "Acquire"
#        contents:
#          - auto: "acquire/*"
#        
#      - section: "Maintain"
#        contents: maintain
#        
#      - section: "Access & Share"
  navbar:
    right:
      - icon: github
        href: https://github.com/hmaier-fws/ak-dm-userguide
        text: GitHub Source
      - href: https://ak-region-dst.gitbook.io/alaska-region-interim-data-management-user-guide
        text: Original Site
        icon: tencent-qq

format:
  html:
#    theme: cerulean
#    smooth-scroll: true
    theme: default
    css: styles.css
    code-block-bg: "000000"
    code-block-border-left: "ffffff"
    date: last-modified
    date-format: iso
    toc: true
    toc-title: On this page
#    number-sections: true
#
#    other-links:
#      - text: Submit an issue
#        icon: github
#        href: https://github.com/hmaier-fws/ak-dm-userguide

# quarto preview --log log.txt --log-level info
# quarto preview source-files --log log.txt --log-level debug

#  latex:
#    toc: true
